FROM fedora:41

# No additional dependencies for null driver
RUN --mount=target=/var/cache/dnf,type=cache,sharing=locked \
    dnf update -y && \
    dnf install -y --nodocs \
    gcc gcc-c++ cmake git
