FROM fedora:41

# SDL2 Dependencies
RUN --mount=target=/var/cache/dnf,type=cache,sharing=locked \
    dnf update -y && \
    dnf install -y --nodocs \
    gcc gcc-c++ cmake git \
    SDL2-devel SDL2_mixer-devel SDL2_ttf-devel
