FROM fedora:41

ARG JOBS=1
ENV JOBS=${JOBS}

RUN --mount=target=/var/cache/dnf,type=cache,sharing=locked \
    dnf update -y && \
    dnf install -y --nodocs \
    gcc gcc-c++ cmake git \
    SDL2-devel SDL2_mixer-devel SDL2_ttf-devel

RUN mkdir -p /haxagon/build
WORKDIR /haxagon/build
COPY linux-sdl2/build.sh /haxagon/build.sh

CMD /haxagon/build.sh
