# SPDX-FileCopyrightText: 2025 AJ Walter, see driver/SFML/README.md for MIT usage.
# SPDX-License-Identifier: GPL-3.0-or-later OR MIT

FROM fedora:41

# SFML dependencies, see https://www.sfml-dev.org/faq/build-use/#link-static
RUN --mount=target=/var/cache/dnf,type=cache,sharing=locked \
    dnf update -y && \
    dnf install -y --nodocs \
    gcc gcc-c++ cmake git \
    freetype-devel ghc-OpenGL-devel libudev-devel  \
    libogg-devel libvorbis-devel openal-soft-devel flac-devel \
    libX11-devel libXrandr-devel libXcursor-devel
