# SPDX-FileCopyrightText: 2025 AJ Walter, see driver/SDL2/README.md for MIT usage.
# SPDX-License-Identifier: GPL-3.0-or-later OR MIT

FROM debian:buster

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
    build-essential make cmake wget autogen autoconf automake ca-certificates git

WORKDIR /root

# Downloading the x86 cross compile builder (miyoomini-toolchain-buildroot-aarch64 is for building on M CPU Macs)
RUN wget https://github.com/shauninman/miyoomini-toolchain-buildroot/releases/download/v0.0.3/miyoomini-toolchain.tar.xz && \
    tar -xvf miyoomini-toolchain.tar.xz && \
    mv miyoomini-toolchain /opt && \
    rm miyoomini-toolchain.tar.xz

# We don't actually need to build the SDL2 libraries for this toolchain, they have already been built
RUN SDL2_VER=2.0.20 && \
    SDL2_PACKAGE=SDL2 && \
    wget https://github.com/libsdl-org/SDL/releases/download/release-${SDL2_VER}/${SDL2_PACKAGE}-${SDL2_VER}.tar.gz && \
    tar -xzf ${SDL2_PACKAGE}-${SDL2_VER}.tar.gz ${SDL2_PACKAGE}-${SDL2_VER}/include && \
    mv ${SDL2_PACKAGE}-${SDL2_VER}/include /opt/miyoomini-toolchain/include/SDL2 && \
    rm -rf ${SDL2_PACKAGE}*

RUN SDL2_VER=2.0.5 \
    SDL2_PACKAGE=SDL2_image \
    SDL2_HEADER=SDL_image.h && \
    wget https://www.libsdl.org/projects/SDL_image/release/${SDL2_PACKAGE}-${SDL2_VER}.tar.gz && \
    tar -xzf ${SDL2_PACKAGE}-${SDL2_VER}.tar.gz ${SDL2_PACKAGE}-${SDL2_VER}/${SDL2_HEADER} && \
    mv ${SDL2_PACKAGE}-${SDL2_VER}/${SDL2_HEADER} /opt/miyoomini-toolchain/include/SDL2 && \
    rm -rf ${SDL2_PACKAGE}*

RUN SDL2_VER=2.0.4 \
    SDL2_PACKAGE=SDL2_mixer \
    SDL2_HEADER=SDL_mixer.h && \
    wget https://www.libsdl.org/projects/SDL_mixer/release/${SDL2_PACKAGE}-${SDL2_VER}.tar.gz && \
    tar -xzf ${SDL2_PACKAGE}-${SDL2_VER}.tar.gz ${SDL2_PACKAGE}-${SDL2_VER}/${SDL2_HEADER} && \
    mv ${SDL2_PACKAGE}-${SDL2_VER}/${SDL2_HEADER} /opt/miyoomini-toolchain/include/SDL2 && \
    rm -rf ${SDL2_PACKAGE}*

RUN SDL2_VER=2.0.14 \
    SDL2_PACKAGE=SDL2_ttf \
    SDL2_HEADER=SDL_ttf.h && \
    wget https://www.libsdl.org/projects/SDL_ttf/release/${SDL2_PACKAGE}-${SDL2_VER}.tar.gz && \
    tar -xzf ${SDL2_PACKAGE}-${SDL2_VER}.tar.gz ${SDL2_PACKAGE}-${SDL2_VER}/${SDL2_HEADER} && \
    mv ${SDL2_PACKAGE}-${SDL2_VER}/${SDL2_HEADER} /opt/miyoomini-toolchain/include/SDL2 && \
    rm -rf ${SDL2_PACKAGE}*

# If you'd like to use a local copy of the libraries, swap the lines below.
#COPY ./miyoo/lib.tar.gz ./
RUN wget -O ./lib.tar.gz https://github.com/RedTopper/Super-Haxagon/releases/download/miyoo-libs/lib.tar.gz

RUN tar -xzf lib.tar.gz && \
    mv lib/* /opt/miyoomini-toolchain/lib && \
    cd /opt/miyoomini-toolchain/lib && \
    ln -s libSDL2-2.0.so.0 libSDL2.so && \
    ln -s libSDL2_image-2.0.so.0 libSDL2_image.so && \
    ln -s libSDL2_mixer-2.0.so.0 libSDL2_mixer.so && \
    ln -s libSDL2_ttf-2.0.so.0 libSDL2_ttf.so && \
    ln -s libjson-c.so.5 libjson-c.so && \
    ln -s libz.so.1 libz.so

ENV PATH="/root/git/tools/miyoo:${PATH}"
