FROM fedora:41

RUN --mount=target=/var/cache/dnf,type=cache,sharing=locked \
    dnf update -y && \
    dnf install -y --nodocs \
    gcc gcc-c++ cmake git \
    freetype-devel ghc-OpenGL-devel libudev-devel  \
    libogg-devel libvorbis-devel openal-soft-devel flac-devel \
    libX11-devel libXrandr-devel libXcursor-devel
