FROM fedora:41

ARG JOBS=1
ENV JOBS=${JOBS}

RUN --mount=target=/var/cache/dnf,type=cache,sharing=locked \
    dnf update -y && \
    dnf install -y --nodocs \
    gcc gcc-c++ cmake git \
    freetype-devel ghc-OpenGL-devel libudev-devel  \
    libogg-devel libvorbis-devel openal-soft-devel flac-devel \
    libX11-devel libXrandr-devel libXcursor-devel

# Build SFML 2.6
RUN mkdir -p /root/sfml
WORKDIR /root/sfml
RUN git clone --branch 2.6.x --depth=1 https://github.com/SFML/SFML.git .
RUN mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=FALSE .. && make -j${JOBS}

ENV PATH="/root/git/tools/linux:${PATH}"
