FROM dockcross/linux-arm64-full

ARG JOBS=1
ENV JOBS=${JOBS}

ENV TOOLCHAIN_ROOT=/buildroot/aarch64-buildroot-linux-gnu/sysroot
ENV TOOLCHAIN_TRIPLE=aarch64-linux-gnu

WORKDIR /root

RUN wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.26.2.tar.gz -O SDL2.tar.gz && \
    wget https://github.com/libsdl-org/SDL_ttf/archive/refs/tags/release-2.0.18.tar.gz -O SDL2_ttf.tar.gz && \
    wget https://github.com/libsdl-org/SDL_mixer/archive/refs/tags/release-2.6.0.tar.gz -O SDL2_mixer.tar.gz

# Install more compatible SDL2
RUN rm $TOOLCHAIN_ROOT/usr/lib64/libSDL2.* && \
    rm -rf $TOOLCHAIN_ROOT/usr/lib64/libSDL2-2.0.so* && \
    tar -xzf SDL2.tar.gz && \
    cd SDL-release-2.26.2 && \
    ./configure --prefix=$TOOLCHAIN_ROOT/usr --host=$TOOLCHAIN_TRIPLE && \
    make -j${JOBS} && \
    make install && \
    /sbin/ldconfig && \
    cd .. && rm -rf SDL2.tar.gz SDL-release-2.26.2

# Install SDL_ttf release 2.0.18 for TTF_SetFontSize support
RUN rm $TOOLCHAIN_ROOT/usr/lib64/libSDL2_ttf.* && \
    rm -rf $TOOLCHAIN_ROOT/usr/lib64/libSDL2_ttf-2.0.so* && \
    tar -xzf SDL2_ttf.tar.gz && \
    cd SDL_ttf-release-2.0.18 && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=$TOOLCHAIN_ROOT/usr -DBUILD_SHARED_LIBS=TRUE .. && \
    make all install && \
    /sbin/ldconfig && \
    cd .. && rm -rf SDL2_ttf.tar.gz SDL_ttf-release-2.0.18

# Install SDL_mixer release 2.6.0 for Mix_GetMusicPosition support
RUN rm $TOOLCHAIN_ROOT/usr/lib64/libSDL2_mixer.* && \
    rm -rf $TOOLCHAIN_ROOT/usr/lib64/libSDL2_mixer-2.0.so* && \
    tar -xzf SDL2_mixer.tar.gz && \
    cd SDL_mixer-release-2.6.0 && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=$TOOLCHAIN_ROOT/usr -DSDL2MIXER_OPUS=OFF -DSDL2MIXER_FLAC=OFF -DSDL2MIXER_MOD=OFF -DSDL2MIXER_MIDI=OFF -DBUILD_SHARED_LIBS=ON .. && \
    make all install && \
    /sbin/ldconfig && \
    cd .. && rm -rf SDL2_mixer.tar.gz SDL_mixer-release-2.6.0

RUN mkdir -p /haxagon/build
WORKDIR /haxagon/build
COPY portmaster/build.sh /haxagon/build.sh

CMD /haxagon/build.sh
