# SPDX-FileCopyrightText: 2025 AJ Walter
# SPDX-License-Identifier: GPL-3.0-or-later OR MIT

FROM devkitpro/devkitarm

# Add tools to build bannertool and makerom
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    apt-get update && \
    apt-get -y --no-install-recommends install gcc g++

# Build bannertool
RUN mkdir -p /root/bannertool
WORKDIR /root/bannertool
RUN git clone --depth=1 https://github.com/RedTopper/bannertool .
RUN mkdir build && cd build && cmake .. && make -j"$(nproc)"
RUN cp build/bannertool /opt/devkitpro/tools/bin

# Build makerom
RUN mkdir -p /root/Project_CTR
WORKDIR /root/Project_CTR
RUN git clone --depth=1 https://github.com/3DSGuy/Project_CTR.git .
RUN cd makerom && make deps && make -j"$(nproc)"
RUN cp makerom/bin/makerom /opt/devkitpro/tools/bin
