FROM fedora:41

RUN --mount=target=/var/cache/dnf,type=cache,sharing=locked \
    dnf update -y && \
    dnf install -y --nodocs \
    gcc gcc-c++ cmake git wget which makeinfo php xxd \
    binutils-devel gmp-devel mpfr-devel libmpc-devel \
    zlib-devel boost-program-options boost-devel python3.11-devel

# Build ndless toolchain
RUN mkdir -p /opt/ndless
WORKDIR /opt/ndless
RUN git clone --depth=1 https://github.com/ndless-nspire/Ndless.git . && \
    git -c submodule.freetype2.update=none submodule update --init --depth=1 --recursive
RUN cd ndless-sdk/thirdparty/freetype2 && \
    git clone https://github.com/freetype/freetype.git . && \
    git reset --hard 069083cccd73d1d68da68116c8d050bb62cdfe0e

# This will take a while... Grab a coffee?
RUN cd ndless-sdk/toolchain && PARALLEL=-j${nproc} PYTHON=/usr/bin/python3.11 ./build_toolchain.sh && rm -r ./download
ENV PATH="/opt/ndless/ndless-sdk/toolchain/install/bin:/opt/ndless/ndless-sdk/bin:${PATH}"
ENV NDLESS="/opt/ndless"
RUN make -j${nproc}
