FROM fedora:41

ARG JOBS=1
ENV JOBS=${JOBS}

RUN --mount=target=/var/cache/dnf,type=cache,sharing=locked \
    dnf update -y && \
    dnf install -y --nodocs \
    gcc gcc-c++ cmake git wget which makeinfo php xxd \
    binutils-devel gmp-devel mpfr-devel libmpc-devel \
    zlib-devel boost-program-options boost-devel python3.11-devel

# Build ndless toolchain
RUN mkdir -p /opt/ndless
WORKDIR /opt/ndless
RUN git clone --depth=1 --recurse-submodules --shallow-submodules https://github.com/ndless-nspire/Ndless.git .

# This will take a while... Grab a coffee?
# If it's taking a very long time, make sure you set the JOBS build argument to equal your CPU cores with '--build-arg JOBS=32'
RUN cd ndless-sdk/toolchain && PARALLEL=-j${JOBS} PYTHON=/usr/bin/python3.11 ./build_toolchain.sh && rm -r ./download
ENV PATH="/opt/ndless/ndless-sdk/toolchain/install/bin:/opt/ndless/ndless-sdk/bin:${PATH}"
ENV NDLESS="/opt/ndless"
RUN make -j${JOBS}

RUN mkdir -p /haxagon/build
WORKDIR /haxagon/build
COPY nspire/build.sh /haxagon/build.sh

CMD /haxagon/build.sh
