# SPDX-FileCopyrightText: 2025 AJ Walter
# SPDX-License-Identifier: GPL-3.0-or-later OR MIT

name: Build SuperHaxagon

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - .github/workflows/build-super-haxagon.yml
      - source/**
      - driver/**
      - CMakeLists.txt
      - CMakeSettings.json
      - net.awalter.SuperHaxagon.yml
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/build-super-haxagon.yml
      - source/**
      - driver/**
      - CMakeLists.txt
      - CMakeSettings.json
      - net.awalter.SuperHaxagon.yml

env:
  REPO: ghcr.io/${{ github.repository }}
  ROMFS_TEXT: "Place the 'romfs' folder from the GitHub release here (the whole romfs folder, not the contents!) or the game will not launch."
  ROMFS_PLACEHOLDER: "PLACE_ROMFS_FOLDER_HERE.txt"
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  # First, try and build the example driver before spending time with the more expensive runners (like macOS)
  build-test:
    name: Test Compile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/redtopper/super-haxagon/example:latest
      options: --user root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          mkdir -p artifacts/build artifacts/install
          cd artifacts/build
          CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install" ../../driver/Example/build.sh

  # Matrix of special platforms SuperHaxagon supports
  build-with-containers:
    name: Build ${{ matrix.containers.artifact }}
    runs-on: ${{ matrix.containers.os }}
    needs: build-test
    strategy:
      matrix:
        containers:
          - build: 'SFML-Linux'
            container: ghcr.io/redtopper/super-haxagon/linux:latest
            artifact: SFML-Linux-x86_64
            cache: 'yes'
            romfs: 'no'
            os: ubuntu-latest

          - build: 'SDL2-Linux'
            container: ghcr.io/redtopper/super-haxagon/linux-sdl2:latest
            artifact: SDL2-Linux-x86_64
            cache: 'no'
            romfs: 'no'
            os: ubuntu-latest

          - build: 'SDL2-Miyoo'
            container: ghcr.io/redtopper/super-haxagon/miyoo:latest
            artifact: SDL2-MiyooMini-armhf
            cache: 'no'
            romfs: 'no'
            os: ubuntu-latest

          - build: 'SDL2-PortMaster'
            container: docker.io/monkeyx/retro_builder:arm64
            artifact: SDL2-PortMaster-arm64
            cache: 'no'
            romfs: ${{ (contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master') && 'yes' || 'no' }}
            os: ubuntu-24.04-arm

          - build: 'N3DS'
            container: ghcr.io/redtopper/super-haxagon/n3ds:latest
            artifact: 3DS-armhf
            cache: 'yes'
            romfs: 'yes'
            os: ubuntu-latest

          - build: 'Nspire'
            container: ghcr.io/redtopper/super-haxagon/nspire:latest
            artifact: Nspire-armel
            cache: 'no'
            romfs: 'yes'
            os: ubuntu-latest

          - build: 'Switch'
            container: docker.io/devkitpro/devkita64:latest
            artifact: Switch-arm64
            cache: 'no'
            romfs: 'yes'
            os: ubuntu-latest

    container:
      image: ${{ matrix.containers.container }}
      options: --user root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Deps
        if: matrix.containers.cache == 'yes'
        uses: actions/cache@v4
        with:
          path: artifacts/build/_deps
          key: deps-${{ matrix.containers.artifact }}-${{ hashFiles('.github/workflows/**', 'CMakeLists.txt', 'cmake/**') }}
          restore-keys: deps-${{ matrix.containers.artifact }}-

      - name: Build SuperHaxagon
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          mkdir -p artifacts/build artifacts/install
          cd artifacts/build
          CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install" ../../driver/${{ matrix.containers.build }}/build.sh

      - name: Delete RomFS
        if: matrix.containers.romfs == 'no'
        run: |
          set -e
          romfs_dir=$(find artifacts/install -type d -name romfs -print -quit)
          if [ -n "$romfs_dir" ]; then
            parent_dir="$(dirname "$romfs_dir")"
            rm -rf "$romfs_dir"
            echo "$ROMFS_TEXT" > "$parent_dir/$ROMFS_PLACEHOLDER"
          fi

      - name: Upload Artifact
        if: matrix.containers.build != 'N3DS'
        uses: actions/upload-artifact@v4
        with:
          name: SuperHaxagon-${{ matrix.containers.artifact }}${{ matrix.containers.romfs == 'no' && '-no-romfs' || '' }}
          compression-level: 9
          path: artifacts/install

        # Special uploads for 3DS
      - name: Upload 3DS 3DSX
        if: matrix.containers.build == 'N3DS'
        uses: actions/upload-artifact@v4
        with:
          name: SuperHaxagon-${{ matrix.containers.artifact }}.3dsx
          compression-level: 9
          path: |
            artifacts/install/*.3dsx
            artifacts/install/**/*.md
            artifacts/install/*.txt
      - name: Upload 3DS CIA
        if: matrix.containers.build == 'N3DS'
        uses: actions/upload-artifact@v4
        with:
          name: SuperHaxagon-${{ matrix.containers.artifact }}.cia
          compression-level: 9
          path: |
            artifacts/install/*.cia
            artifacts/install/**/*.md
            artifacts/install/*.txt

  # Builds SuperHaxagon natively (as in, without containers)
  build-native:
    name: Build ${{ matrix.platforms.artifact }}
    runs-on: ${{ matrix.platforms.os }}
    needs: build-test
    strategy:
      matrix:
        platforms:
          - artifact: SFML-Linux-arm64
            os: ubuntu-24.04-arm
          - artifact: SFML-macOSBrewUnix-arm64
            os: macos-latest
          - artifact: SFML-Windows-x86_64
            os: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Deps
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: deps-${{ matrix.platforms.artifact }}-${{ hashFiles('.github/workflows/**', 'CMakeLists.txt', 'cmake/**') }}
          restore-keys: deps-${{ matrix.platforms.artifact }}-

      - name: Install SFML Dependencies (ubuntu)
        if: matrix.platforms.os == 'ubuntu-24.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install  -y \
            libgl1-mesa-dev \
            libudev-dev \
            libopenal-dev \
            libvorbis-dev \
            libflac-dev \
            libx11-dev \
            libxrandr-dev \
            libx11-xcb-dev \
            libxcb-randr0-dev \
            libxcb-image0-dev \
            libxcursor-dev \
            libjpeg-dev \
            libfreetype-dev

      - name: Install SFML Dependencies (macOS)
        if: matrix.platforms.os == 'macos-latest'
        run: |
          brew install openal-soft
          brew install sfml@2

      - name: Build SuperHaxagon
        run: |
          cmake -E make_directory build install
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DCMAKE_FIND_FRAMEWORK=LAST
          cmake --build build --config Release --target install --parallel 6

      - name: Delete RomFS
        shell: bash
        run: |
          set -e
          rm -rf install/romfs
          echo "$ROMFS_TEXT" > "install/$ROMFS_PLACEHOLDER"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SuperHaxagon-${{ matrix.platforms.artifact }}-no-romfs
          compression-level: 9
          path: install

  build-macos-bundle:
    name: Build macOS Bundle
    if: contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    runs-on: macos-latest
    needs: build-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Deps
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: deps-SuperHaxagon-macOS-arm-${{ hashFiles('.github/workflows/**', 'CMakeLists.txt', 'cmake/**') }}
          restore-keys: deps-SuperHaxagon-macOS-arm-

      - name: Build SuperHaxagon
        run: |
          cmake -E make_directory build install
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_BUNDLE=TRUE
          cmake --build build --config Release --target install --parallel 6

        # See: https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/
      - name: Codesign App Bundle
        env:
          MACOS_CERTIFICATE: ${{ secrets.APPLE_CERT_DATA }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.APPLE_CERT_PASSWORD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.APPLE_CERT_ID }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.APPLE_CERT_KEYCHAIN_PASSWORD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12

          security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain

          /usr/bin/codesign --deep --force -s "$MACOS_CERTIFICATE_NAME" --options runtime install/SuperHaxagon.app -v

          cd install
          tar -cvf SuperHaxagon-SFML-macOS-arm64.tar *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SuperHaxagon-SFML-macOS-arm64
          compression-level: 9
          path: install/SuperHaxagon-SFML-macOS-arm64.tar

  # Build flatpak repo
  build-flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    needs: build-test
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build SuperHaxagon
        uses: flatpak/flatpak-github-actions/flatpak-builder@fc80c13788c1ba0f45add99b19cf26b616ccab4f # v6.4
        with:
          bundle: net.awalter.SuperHaxagon.flatpak
          manifest-path: net.awalter.SuperHaxagon.yml
          upload-artifact: false

      - name: Prepare Release
        run: |
          mkdir install
          cp net.awalter.SuperHaxagon.flatpak install
          cp flatpak_app/files/v*.txt flatpak_app/files/*.md install
          cp -r flatpak_app/files/licenses install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net.awalter.SuperHaxagon-x86_64
          compression-level: 9
          path: install

  # Finally, if all pipelines work, upload the current RomFS
  upload-romfs:
    name: Upload RomFS
    runs-on: ubuntu-latest
    needs:
      - build-flatpak
      - build-native
      - build-with-containers
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Move RomFS
        run: |
          mkdir upload
          mv romfs upload

      - name: Upload RomFS
        uses: actions/upload-artifact@v4
        with:
          name: romfs
          compression-level: 9
          path: upload
